[package]
name = "rust_quant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[workspace]
#members = ["quant_job", "my_library"]

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "full"] }
reqwest = "0.11.27"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"

hmac = "0.12.1"
sha2 = "0.10.8"
chrono = "0.4.38"
hex = "0.4.3"
anyhow = "1.0.86"
base64 = "0.21.7"
thiserror = "1.0.61"


rbs = { version = "4.5" }
#rbdc-sqlite = { version = "4.5", default-features = false, features = ["tls-native-tls"] }
rbdc-mysql = { version = "4.5", default-features = false, features = ["tls-native-tls"] }
#rbdc-pg={version="4.5", default-features = false, features = ["tls-native-tls"]}
#rbdc-mssql={version="4.5", default-features = false, features = ["tls-native-tls"]}
rbatis = { version = "4.5", features = ["debug_mode"]}

log = "0.4"
fast_log = "1.6"
clap = { version = "4.5.4", features = ["derive"] }

tokio-tungstenite = { version = "0.23", features = ["native-tls"] }
futures-channel = "0.3.30"
futures-util = "0.3.30"
env_logger = "0.11.3"


tracing = "0.1"
tracing-subscriber = "0.3.0"
tracing-appender = "0.2.3"
hmac-sha256 = "0.1"
dotenv = "0.15.0"
ta = "0.5.0"
futures = "0.3.30"
redis = { version = "0.25.3", features = ["aio", "tokio-comp"] }



[dependencies]
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "full"] }
reqwest = "0.11.27"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
hmac = "0.12.1"
sha2 = "0.10.8"
chrono = "0.4.38"
hex = "0.4.3"
anyhow = "1.0.86"
base64 = "0.21.7"
thiserror = "1.0.61"


rbs = { version = "4.5" }
#rbdc-sqlite = { version = "4.5", default-features = false, features = ["tls-native-tls"] }
rbdc-mysql = { version = "4.5", default-features = false, features = ["tls-native-tls"] }
#rbdc-pg={version="4.5", default-features = false, features = ["tls-native-tls"]}
#rbdc-mssql={version="4.5", default-features = false, features = ["tls-native-tls"]}
rbatis = { version = "4.5" }

log = "0.4"
flexi_logger = "0.28.3"

fast_log = "1.6"
clap = { version = "4.5.4", features = ["derive"] }

tokio-tungstenite = { version = "0.23", features = ["native-tls"] }
futures-channel = "0.3.30"
futures-util = "0.3.30"
env_logger = "0.11.3"


tracing = "0.1"
tracing-subscriber = { version = "0.3.0", features = ["env-filter", "json"] }
tracing-appender = "0.2.3"
hmac-sha256 = "0.1"
dotenv = "0.15.0"
ta = "0.5.0"

futures = "0.3.30"
redis = { version = "0.25.3", features = ["aio", "tokio-comp"] }

tokio-retry = "0.3.0"
once_cell = "1.19.0"
lazy_static = "1.4.0"

#邮件服务
lettre = "0.11"